//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class Matrix
		{
			private int NumRows;
			private int NumCol;
			private double[,] Values;

			public Matrix(int row, int col)
			{
				this.NumRows = row;
				this.NumCol = col;
				this.Values = new double[row,col];
			}			

			public void Set(int i, int j, double entry)
			{
				if (i < this.NumRows)
				{
					if (j < this.NumCol)
					{
						Values[i,j]=entry;
					}
				}
			}

}

